-- 创建vMOS数据表
CREATE TABLE IF NOT EXISTS `vmos_data` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_id` varchar(255) DEFAULT NULL COMMENT '任务ID（关联client_task_info表的task_id）',
  `sequence_number` varchar(50) DEFAULT NULL COMMENT '序号',
  `speed` varchar(50) DEFAULT NULL COMMENT '速率',
  `resolution` varchar(100) DEFAULT NULL COMMENT '分辨率',
  `rtt` varchar(50) DEFAULT NULL COMMENT 'RTT',
  `packet_loss_rate` varchar(50) DEFAULT NULL COMMENT '丢包率',
  `stutter_ratio` varchar(50) DEFAULT NULL COMMENT '卡顿占比',
  `initial_buffering_delay` varchar(50) DEFAULT NULL COMMENT '初缓时延',
  `bitrate` varchar(50) DEFAULT NULL COMMENT '码率',
  `calculated_resolution` varchar(50) DEFAULT NULL COMMENT '计算分辨率',
  `video_experience` varchar(50) DEFAULT NULL COMMENT '视频体验',
  `interaction_experience` varchar(50) DEFAULT NULL COMMENT '交互体验',
  `presentation_experience` varchar(50) DEFAULT NULL COMMENT '呈现体验',
  `s_lost_packet_rate` varchar(50) DEFAULT NULL COMMENT '丢包率（s_lost_packet_rate）',
  `s_stall_rate` varchar(50) DEFAULT NULL COMMENT '卡顿占比（s_stall_rate）',
  `alpha` varchar(50) DEFAULT NULL COMMENT 'α',
  `beta` varchar(50) DEFAULT NULL COMMENT 'β',
  `vmos` varchar(50) DEFAULT NULL COMMENT 'vMOS',
  `avg_qoe` varchar(50) DEFAULT NULL COMMENT 'avgQOE',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(4) DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_deleted` (`deleted`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='vMOS数据表';

