-- 创建网络侧数据表
CREATE TABLE IF NOT EXISTS `network_data` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `serial_no` varchar(100) DEFAULT NULL COMMENT '序列号',
  `time_stamp` varchar(50) DEFAULT NULL COMMENT '时间戳',
  `start_time` varchar(50) DEFAULT NULL COMMENT '开始时间',
  `gpsi` varchar(100) DEFAULT NULL COMMENT 'GPSI',
  `dnn` varchar(100) DEFAULT NULL COMMENT 'DNN',
  `s_nssai` varchar(100) DEFAULT NULL COMMENT 'S-NSSAI',
  `rat_type` varchar(50) DEFAULT NULL COMMENT 'RAT类型',
  `qci` varchar(50) DEFAULT NULL COMMENT 'QCI',
  `exp_opt_flag` varchar(50) DEFAULT NULL COMMENT '体验优化标志',
  `exp_opt_start_time` varchar(50) DEFAULT NULL COMMENT '体验优化开始时间',
  `app_id` varchar(100) DEFAULT NULL COMMENT '应用ID',
  `sub_app_id` varchar(100) DEFAULT NULL COMMENT '子应用ID',
  `app_status` varchar(50) DEFAULT NULL COMMENT '应用状态',
  `app_quality` varchar(50) DEFAULT NULL COMMENT '应用质量',
  `tai` varchar(100) DEFAULT NULL COMMENT 'TAI',
  `cell_id` varchar(100) DEFAULT NULL COMMENT '小区ID',
  `delay_an` varchar(50) DEFAULT NULL COMMENT '下行时延',
  `delay_dn` varchar(50) DEFAULT NULL COMMENT '上行时延',
  `uplink_bandwidth` varchar(50) DEFAULT NULL COMMENT '上行带宽',
  `downlink_bandwidth` varchar(50) DEFAULT NULL COMMENT '下行带宽',
  `uplink_pkg` varchar(50) DEFAULT NULL COMMENT '上行包数',
  `downlink_pkg` varchar(50) DEFAULT NULL COMMENT '下行包数',
  `lost_uplink_pkg` varchar(50) DEFAULT NULL COMMENT '丢失上行包数',
  `lost_downlink_pkg` varchar(50) DEFAULT NULL COMMENT '丢失下行包数',
  `sub_app_start_time` varchar(50) DEFAULT NULL COMMENT '子应用开始时间',
  `info_indicate` varchar(100) DEFAULT NULL COMMENT '信息指示',
  `upfld` varchar(100) DEFAULT NULL COMMENT 'UPFLD',
  `pei` varchar(100) DEFAULT NULL COMMENT 'PEI',
  `sub_app_eff_duration` varchar(50) DEFAULT NULL COMMENT '子应用有效时长',
  `max_delay_an` varchar(50) DEFAULT NULL COMMENT '最大下行时延',
  `max_delay_dn` varchar(50) DEFAULT NULL COMMENT '最大上行时延',
  `avg_bandwidth_ui` varchar(50) DEFAULT NULL COMMENT '平均上行带宽',
  `avg_bandwidth_di` varchar(50) DEFAULT NULL COMMENT '平均下行带宽',
  `max_bandwidth_ui` varchar(50) DEFAULT NULL COMMENT '最大上行带宽',
  `max_bandwidth_di` varchar(50) DEFAULT NULL COMMENT '最大下行带宽',
  `volume_ui` varchar(50) DEFAULT NULL COMMENT '上行流量',
  `volume_di` varchar(50) DEFAULT NULL COMMENT '下行流量',
  `exp_opt_end_time` varchar(50) DEFAULT NULL COMMENT '体验优化结束时间',
  `sub_app_edr_start_time` varchar(50) DEFAULT NULL COMMENT '子应用EDR开始时间',
  `user_service_load_ui_ecn` varchar(50) DEFAULT NULL COMMENT '用户服务负载上行ECN',
  `user_service_load_di_ecn` varchar(50) DEFAULT NULL COMMENT '用户服务负载下行ECN',
  `assurance_failed_reason` varchar(200) DEFAULT NULL COMMENT '保障失败原因',
  `gnb_qnc_notif_type` varchar(50) DEFAULT NULL COMMENT 'gNB QNC通知类型',
  `avg_qoe` varchar(50) DEFAULT NULL COMMENT '平均QoE',
  `max_resolution` varchar(100) DEFAULT NULL COMMENT '最大分辨率',
  `most_resolution` varchar(100) DEFAULT NULL COMMENT '最常见分辨率',
  `max_bit_rate_ui` varchar(50) DEFAULT NULL COMMENT '最大上行码率',
  `avg_bit_rate_ui` varchar(50) DEFAULT NULL COMMENT '平均上行码率',
  `max_bit_rate_di` varchar(50) DEFAULT NULL COMMENT '最大下行码率',
  `avg_bit_rate_di` varchar(50) DEFAULT NULL COMMENT '平均下行码率',
  `stalling_duration` varchar(50) DEFAULT NULL COMMENT '卡顿时长',
  `stalling_number` varchar(50) DEFAULT NULL COMMENT '卡顿次数',
  `service_delay` varchar(50) DEFAULT NULL COMMENT '服务时延',
  `service_initial_duration` varchar(50) DEFAULT NULL COMMENT '服务初始时长',
  `file_name` varchar(255) DEFAULT NULL COMMENT '文件名（用于标识来源）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(4) DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_file_name` (`file_name`),
  KEY `idx_gpsi` (`gpsi`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_cell_id` (`cell_id`),
  KEY `idx_time_stamp` (`time_stamp`),
  KEY `idx_deleted` (`deleted`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网络侧数据表';

