server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: case-execute-service

# 用例执行配置
case:
  execution:
    # 单个用例执行超时时长（分钟），默认5分钟
    timeout-minutes: 5

# gohttpserver配置
gohttpserver:
  url: http://localhost:8081
